[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "vcdisk"
authors = [{name = "Lorenzo Posti", email = "lorenzo.posti@gmail.com"}]
dynamic = ["version", "description"]
